services:
  slack_clone:
    image: ${DOCKER_USERNAME}/slack_clone:v1.0.0-demo
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 3333
      NODE_ENV: production
      APP_KEY: ${APP_KEY}
      APP_NAME: slek-server
      DRIVE_DISK: local
      DB_CONNECTION: pg
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT:-5432}
      PG_USER: ${PG_USER:-vpwa_user}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB_NAME: ${PG_DB_NAME:-vpwa}
      DEMO_LOCKED: ${DEMO_LOCKED:-true}
    networks:
      - internal

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - slack_clone
    networks:
      - internal

networks:
  internal:
    mode: bridge
